# Generated by Django 3.2.5 on 2021-07-15 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beers',
            new_name='Beer',
        ),
    ]
