# Generated by Django 3.2.5 on 2021-07-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_rename_beers_beer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='beer',
            name='size',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
