# Generated by Django 3.2.5 on 2021-08-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20210715_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='size',
        ),
    ]
