# Generated by Django 3.2.5 on 2021-08-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_beer_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐ ⭐'), (3, '⭐ ⭐ ⭐'), (4, '⭐ ⭐ ⭐ ⭐'), (5, '⭐ ⭐ ⭐ ⭐ ⭐')], default=3),
        ),
    ]
