# Generated by Django 3.2.5 on 2021-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_alter_beerreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=3),
        ),
    ]
